# Generated by Django 2.2.9 on 2020-11-30 10:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0005_post_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='title',
        ),
    ]
