# Generated by Django 2.2.6 on 2021-01-04 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0011_auto_20210104_1406'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='image',
            field=models.ImageField(blank=True, help_text='Добавьте изображение для своего поста!', null=True, upload_to='posts/', verbose_name='Изображение'),
        ),
    ]
